name: 🐳 On Master - Build and Test Docker Image

on:
  push:
    branches: ["master"]

jobs:
  build-image:
    name: 🏗️ Build Image
    runs-on: ubuntu-latest

    steps:
      - name: 🐧 Checkout
        uses: actions/checkout@v3

      - name: 📦 Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Login to docker.01-edu.org Registry
        uses: docker/login-action@v2
        with:
          registry: docker.01-edu.org
          username: ${{ secrets.USER_DOCKER_01EDU_ORG }}
          password: ${{ secrets.SECRET_DOCKER_01EDU_ORG }}
    
      - name: 🏗️ Build the Branch-Mobile Docker image
        run: |
          docker build tests/piscine_flutter/ --file tests/piscine_flutter/Dockerfile --tag ghcr.io/01-edu/test-dart:latest
          docker push ghcr.io/01-edu/test-dart:latest
